# Generated by Django 5.2.12 on 2026-03-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0002_language_alter_project_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
    ]
