# Generated by Django 5.2.12 on 2026-05-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0003_remove_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='compatible_projects',
            field=models.ManyToManyField(blank=True, related_name='compatible_libraries', to='configurador.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
