# Generated by Django 5.2.12 on 2026-05-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0004_project_compatible_projects_alter_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UVLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_content', models.TextField()),
            ],
        ),
    ]
