FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    postgresql-client \
    pkg-config \
    libcairo2-dev \
    && rm -rf /var/lib/apt/lists/*
COPY backend /app
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir coverage

CMD ["bash", "-c", "python manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3"]